name: Deploy Alpha.One
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PEM_SSH }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: 'build/'
          REMOTE_HOST: '143.110.220.25'
          REMOTE_USER: 'root'
          TARGET: '/var/www/html'
